### PR TITLE
Introduced acceptSslCerts capability

### LINKED ISSUE #233: support desired_capabilities: acceptSslCerts=True
PhantomJS itself supports ignoring/accepting SSL certs based on a flag when starting the browser, however GhostDriver does not support the ability to accept all SSL certs.  This functionality is supported by the WebDriver spec via desired_capabilities.

Here is a python snippet demonstrating the inability to set `acceptSslCerts=True`

```python
from selenium import webdriver

dcaps = {'acceptSslCerts':True}
browser = webdriver.PhantomJS(desired_capabilities=dcaps)

browser.get('https://<some url with an invalid cert>')
```

At this point the page is not loaded

```
In [5]: browser.page_source
Out[5]: u'<html><head></head><body></body></html>'

In [7]: browser.capabilities['acceptSslCerts']
Out[7]: False
```

Being that PhantomJS and WebDriver support the behavior, GhostDriver should include it as well.

### PR DESCRIPTION
**Pull request by acarpe**
This commit should fix #233, Let me know what do you think.

Capability that allows to access to those sites using self-signed or invalid
certificates, and where the certificate does not match the serving domain as
if the HTTPS was configured properly.
settings
'--web-security=false'
'--ssl-protocol=any'
'--ignore-ssl-errors=true'

Fixed some html tags in the javadoc

### CODE REVIEW

**Comment by mhluongo** [comment]
:+1:

**Comment by detro** [comment]
I'd be happy to merge this.
But this needs to be rebased on `origin/master` because I can't merge it as is.

**Comment by jerrywiltse** [comment]
+1, still an issue

**Comment by jerrywiltse** [comment]
Is this done then, or ready to go?

**Comment by acarpe** [comment]
Now this is really done, in the previous commit I removed the feature because of a wrong squash.

**Comment by jerrywiltse** [comment]
That sounds like good news, but I'm not sure when said changes will make it
into Maven. It seems like the project has a lot of stuff waiting to be
merged in and nobody to do it.

Gerald R. Wiltse
jerrywiltse@gmail.com

**Comment by jamilaryan** [comment]
here is the js code alon with chrome enabled, make sure you have a chrome driver alongside phantom to see it visually:
```
const capabilities = webdriver.Capabilities.phantomjs();
capabilities.set(webdriver.Capability.ACCEPT_SSL_CERTS, true);
capabilities.set(webdriver.Capability.SECURE_SSL, false);
capabilities.set('phantomjs.cli.args', ['--web-security=no', '--ssl-protocol=any', '--ignore-ssl-errors=yes']);
const driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome(), capabilities).build();
```

**Comment by atalis** [comment]
How do I set this in protractor.config.js?  I'm already passing the '--ignore-ssl-errors=yes' parameter on command line:

`phantomjs --webdriver=localhost:4444 --web-security=false --ignore-ssl-errors=true --ssl-protocol=any`

I tried setting webdriver's ACCEPT_SSL_CERTS to true in protractor.config.js file like this:

`capabilities: 
{
    browserName: 'phantomjs',
    'webdriver.Capability.ACCEPT_SSL_CERTS': true,
    'webdriver.Capability.SECURE_SSL': false
  }`

But this is not working.  Here is the dump of the Capabilities during a test case run:

`Capabilities {
  'browserName' => 'phantomjs',
  'version' => '2.1.1',
  'driverName' => 'ghostdriver',
  'driverVersion' => '1.2.0',
  'platform' => 'mac-unknown-64bit',
  'javascriptEnabled' => true,
  'takesScreenshot' => true,
  'handlesAlerts' => false,
  'databaseEnabled' => false,
  'locationContextEnabled' => false,
  'applicationCacheEnabled' => false,
  'browserConnectionEnabled' => false,
  'cssSelectorsEnabled' => true,
  'webStorageEnabled' => false,
  'rotatable' => false,
  'acceptSslCerts' => false,
  'nativeEvents' => true,
  'proxy' => { proxyType: 'direct' } }`

What am I doing wrong?

**Pull request merged**
