### PR TITLE
Ghostdriver should use the --ip value to start the web server

### LINKED ISSUE #390: Allow GhostDriver to bind to a specific IP
I'm trying to run PhantomJS/GhostDriver on OpenShift, where an application is authorized to bind just to a particular IP that is stored, in my setup, in the OPENSHIFT_DIY_IP env variable.

When I run PhantomJS I get this error:

    $ ./phantomjs --webdriver=${OPENSHIFT_DIY_IP}:29234
    PhantomJS is launching GhostDriver...
    [ERROR - 2014-09-09T16:10:18.630Z] GhostDriver - main.fail - {"message":"Could not start Ghost   Driver","line":82,"sourceId":139814638960128,"sourceURL":":/ghostdriver/main.js","stack":"Error:   Could not start Ghost Driver\n    at :/ghostdriver/main.js:82","stackArray":[{"sourceURL":":/ghostdriver/main.js","line":82}]}

As far as I understood, it is not yet possible to specify Ghostdriver the IP it should bind to, but it would be great if that would be possible.

I already opened the [issue](https://github.com/ariya/phantomjs/issues/12553) in PhantomJS but it has been closed, and I was requested to reopen it for Ghostfriver.

### PR DESCRIPTION
**Pull request by laurentj**
Fixes #390

### CODE REVIEW

**Comment by danidemi** [comment]
Any idea on when this fix will be merged ?

**Comment by bernarpa** [comment]
I've built PhantomJS 1.9.8 for Linux x86_64 with this patch, on a CentOS 6.6 system (I needed it in order to use Ghostdriver on OpenShift). If you think it may help, you can find it here: https://paolobernardi.wordpress.com/2015/02/25/phantomjs-with-ghostdriver-on-openshift/

**Comment by rajendraarora16** [comment]
@bernarpa I tried your phantomJS on openshift Server.. But unfortunately. It's not working :( When i run this command `./phantomjs -v` It says permission denied.. :(

**Comment by bernarpa** [comment]
Perhaps you need to do a chmod +x phantomjs before or it's something else?

**Comment by alekciy** [comment]
+1 to merge
https://github.com/ariya/phantomjs/issues/11801

**Comment by detro** [comment]
This is a great fix!
I must have been drunk when I made this mistake: I had even the default `.ip` configuration!

**Pull request merged**
