### PR TITLE
update to selenium 2.53.0

### PR DESCRIPTION
**Pull request by jesg**

### CODE REVIEW

**Comment by anilreddy** [comment]
@detro can you please merge these changes

**Comment by anilreddy** [comment]
@jesg have you ran tests did all of them got passed?

**Comment by jesg** [comment]
@anilreddy there are no regressions created by this change.  i created a [gist](https://gist.github.com/jesg/1f58af7236462841448f4a4ff5036aa7) with the test results when running against phantomjs 2.1.1 on linux.

ghostdriver is having some issues with cookies.  this seems to be partially resolved by pull request ariya/phantomjs#14068.

also there seemed to be some regressions between phantomjs 1.9.8 and phantomjs 2.1.1 that you can see when you run the following in the core selenium project `./go //java/client/test/org/openqa/selenium/phantomjs:test:run haltonfailure=false`.  i'll create issues for these regressions.

**Comment by jesg** [comment]
the following selenium tests failed when i built the phantomjs master branch with the changes from this pull request.  test case `org.openqa.selenium.interactions.CombinedInputActionsTest#testMouseMovementWorksWhenNavigatingToAnotherPage` is the only regression from phantomjs 1.9.8.

```text
org.openqa.selenium.ContentEditableTest#testShouldBeAbleToTypeIntoTinyMCE
org.openqa.selenium.ContentEditableTest#testShouldBeAbleToTypeIntoEmptyContentEditableElement
org.openqa.selenium.ContentEditableTest#testTypingIntoAnIFrameWithContentEditableOrDesignModeSet
org.openqa.selenium.ContentEditableTest#testShouldBeAbleToTypeIntoContentEditableElementWithExistingValue
org.openqa.selenium.ContentEditableTest#testNonPrintableCharactersShouldWorkWithContentEditableOrDesignModeSet
org.openqa.selenium.ContentEditableTest#testShouldAppendToTinyMCE
org.openqa.selenium.CorrectEventFiringTest#testNativelyClickOverlappingElements
org.openqa.selenium.CorrectEventFiringTest#testClickOverlappingElements
org.openqa.selenium.CorrectEventFiringTest#testClickAnElementThatDisappear
org.openqa.selenium.ElementFindingTest#testFindingASingleElementByEmptyTagNameShouldThrow
org.openqa.selenium.ElementFindingTest#testFindingASingleElementByEmptyClassNameShouldThrow
org.openqa.selenium.ElementFindingTest#testFindingMultipleElementsByEmptyNameShouldReturnEmptyList
org.openqa.selenium.ElementFindingTest#testFindingMultipleElementsByEmptyIdShouldReturnEmptyList
org.openqa.selenium.ElementFindingTest#testFindingASingleElementByEmptyNameShouldThrow
org.openqa.selenium.ElementFindingTest#testFindingASingleElementByEmptyIdShouldThrow
org.openqa.selenium.ElementFindingTest#testFindingASingleElementByEmptyCssSelectorShouldThrow
org.openqa.selenium.I18nTest#testShouldBeAbleToActivateIMEEngine
org.openqa.selenium.PageLoadingTest#testShouldTimeoutIfAPageTakesTooLongToRefresh
org.openqa.selenium.PositionAndSizeTest#testShouldGetCoordinatesInViewPortOfAnElementInAFrame
org.openqa.selenium.PositionAndSizeTest#testShouldGetCoordinatesInViewPortOfAnElementInANestedFrame
org.openqa.selenium.VisibilityTest#testShouldNotBeAbleToTypeToAnElementThatIsNotDisplayed
org.openqa.selenium.interactions.BasicMouseInterfaceTest#testMoveRelativeToBody
org.openqa.selenium.interactions.BasicMouseInterfaceTest#testShouldClickElementInIFrame
org.openqa.selenium.interactions.BasicMouseInterfaceTest#testMovingMouseBackAndForthPastViewPort
org.openqa.selenium.interactions.BasicMouseInterfaceTest#testMousePositionIsNotPreservedInActionsChain
org.openqa.selenium.interactions.BasicMouseInterfaceTest#testMovingIntoAnImageEnclosedInALink
org.openqa.selenium.interactions.CombinedInputActionsTest#testShiftClickingOnMultiSelectionList
org.openqa.selenium.interactions.CombinedInputActionsTest#testCombiningShiftAndClickResultsInANewWindow
org.openqa.selenium.interactions.CombinedInputActionsTest#testMouseMovementWorksWhenNavigatingToAnotherPage
org.openqa.selenium.interactions.DragAndDropTest#testDragAndDropElementWithOffsetInIframeAtBottom
org.openqa.selenium.interactions.DragAndDropTest#testDragAndDropToElementInIframe
```

**Comment by anilreddy** [comment]
@jesg I think the changes are good and can be merged according to your gist results. @asolntsev can you please merge these changes to your repo as I think @detro is not active. Because we are greatly depend on phantomjs scripts.

**Comment by jerrywiltse** [comment]
I agree and support this motion :)

Gerald R. Wiltse
jerrywiltse@gmail.com

**Comment by asolntsev** [comment]
@jesg @anilreddy @jerrywiltse I have merged this pull request to our fork: https://github.com/codeborne/ghostdriver

It will be released in version 1.4.0 soon.

**Comment by anilreddy** [comment]
@asolntsev superb..!! Thanks

**Comment by jesg** [comment]
i've written a bash script [script](https://github.com/jesg/ghostdriver/blob/master/bin/ghostdriver) to make phantomjs command line options compatible with ghostdriver.  you should set `PHANTOMJS_GHOSTDRIVER_PATH` environment variable to the path to main.js.

**Comment by asolntsev** [comment]
@jesg Sorry, I am not very advanced in JS part of ghostdriver... What should I do with this script?

**Comment by jesg** [comment]
@asolntsev the selenium python, ruby, and javascript phantomjs drivers do not handle a custom ghostdriver build like the java client.  the java client will set different arguments if a custom ghostdriver is [provided](https://github.com/jesg/ghostdriver/blob/master/binding/java/src/main/java/org/openqa/selenium/phantomjs/PhantomJSDriverService.java#L496).  the phantomjs command line arguments are not compatible with the ghostdriver arguments.

in paticular `--webdriver` phantomjs argument and `--port` ghostdriver argument are not compatible.  the `--webdriver` argument will force the embedded ghostdriver to load and transform the arguments to ghostdriver compatible arguments.  most phantomjs clients use the `--webdriver` option.  i wrote this script as a way for me to run non-java clients on a custom ghostdriver build.  the script transforms the phantomjs command line arguments to ghostdriver command line arguments.

**Pull request merged**
