### PR TITLE
Fixed adding --webdriver-logfile and --webdriver CLI arguments through t...

### PR DESCRIPTION
**Pull request by rayd**
...he phantomjs.cli.args capability. This should take care of #406 and #383.

### CODE REVIEW

**Comment by hydtek** [comment]
This removes the duplication of --webdriver, but when running it I get this error:

Apr 24, 2015 10:35:04 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: C:\Users\shyde\Downloads\Instagram AutoLike\InstagramAutoLike\phantomjs-2.0.0-windows\bin\phantomjs.exe
Apr 24, 2015 10:35:04 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 41533
Apr 24, 2015 10:35:04 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--webdriver=127.0.0.1:6666, --webdriver-logfile=C:\Users\shyde\Downloads\Instagram AutoLike\InstagramAutoLike\phantomjsdriver.log]
Apr 24, 2015 10:35:04 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
[INFO  - 2015-04-24T14:35:06.222Z] GhostDriver - Main - running on port 6666
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'MBC5708', ip: '167.74.185.13', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_45'
Driver info: driver.version: PhantomJSDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:593)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)

**Comment by rayd** [comment]
I think the `webdriver` argument is only supposed to be a port number.

**Comment by hydtek** [comment]
I tried at one point with just a port number, and no luck. But I might not understand fully what --webdriver=port does, I am trying to run my webdriver on a alternate network interface (eth0:1)

**Comment by rayd** [comment]
I believe it's just telling phantomjs what port to interact with the webdriver on. And actually, looking at your logs again, I can see Ghostdriver starting up on port 6666, so I *think* that's working. However the line

```Apr 24, 2015 10:35:04 AM org.openqa.selenium.phantomjs.PhantomJSDriverService 
INFO: port: 41533```

tells me that something's not quite right... I'll try to dig into that later. Just wondering are you seeing this issue only with the changes in this pull request, or are they also in master?

**Comment by hydtek** [comment]
I only notice this in this pull request, since the master doesn't even really let you set --webdriver, since its being overwritten (Duplicated). When looking at the code I believe its the last line " return new PhantomJSDriverService(phantomjs, port, argsBuilder.build(), environment);" Seems like when port mismatches --webdriver port it blows up, but this could be a bigger issue. 

Also on webpage http://phantomjs.org/api/command-line.html, it states 
--webdriver = can be "--webdriver starts in 'Remote WebDriver mode' (embedded GhostDriver): '[[:]]' (default '127.0.0.1:8910')" which is why I thought it could accept ip:port

**Comment by detro** [comment]
Thanks.
this is a great catch!

**Comment by marklagendijk** [comment]
@detro when will the next version of ghostdriver (including this fix) be released?

**Comment by anilreddy** [comment]
@marklagendijk detro is no longer maintaining this project latest ghostdriver can be found here: https://github.com/codeborne/ghostdriver

**Comment by jerrywiltse** [comment]
Perhaps Ivan can update the readme to also mention the codeborne fork ?

Gerald R. Wiltse
jerrywiltse@gmail.com

**Comment by marklagendijk** [comment]
@detro, @anilreddy, @jerrywiltse I think updating the README to mention the fork would be a good idea. It might be even better to instead transfer the repository itself to @codeborne, or at least add them as maintainers.
@ariya is there any reason why PhantomJS isn't using this latest (forked) version of Ghostdriver? It is a pity to see that time is being wasted on issues which are already fixed in the latest code.

**Pull request merged**
