### PR TITLE
fixed session_request_handler to handle POSTs to /file, relying on phantom's page.uploadFile

### PR DESCRIPTION
**Pull request by Whoaa512**
Should fix #282 
related phantomjs PR: ariya/phantomjs#12030

### CODE REVIEW

**Comment by RongxinZhang** [comment]
@Whoaa512 - I am experiencing the problem with uploadfile using Nightwatchjs.

@detro - Would really appreciate help with this.

I'm using Nightwatchjs version 0.6.11 and phantomjs version 2.0.

this is my code:
```
browser
      .click(TAB_Images)
      .assert.visible('#images')
      .verify.visible(FRM_Icon)
      .setValue('input#uploadingIcon', '/Users/rongxinz/repos/retsly/www/public/images/apps/05.png')
```

But it just hangs up on:
```
 ✔ Testing if element <#uploadingIcon> is visible.
```

This is my HTML input form:
```
input(type="file" data-hook='appIconText' id="uploadingIcon")
```

It works when I run this in chrome and firefox. but hangs in phantomjs

I think it its the setValue, but never completes.

**Comment by RongxinZhang** [comment]
FUCKING FIXED IT! WELL Justysed Pahntomjs 1.9.8

https://bitbucket.org/ariya/phantomjs/downloads

**Comment by sebastian3495** [comment]
@RongxinZhang I got phantomjs 2.1.1, but I cant get it working. Should I install nightwatchjs as well, the problem is that there is no souch ".setValue" attritbute in "python phantomjs."
But maybe its because you are using "javascript phantomjs" ?

If thats the case, how should I fix it in python? (if u know that)

**Comment by aaaskew** [comment]
I am note sure if it is worth noting but I found the following useful (https://github.com/ariya/phantomjs/issues/13302#issuecomment-158628631).  It explains why I was not able to use upload_file method in the Perl Selenium-Remote-Driver when connecting to a local PhantomJS 2.1.1 using the webdriver protocol.

It looks to me as if the Selenium webdriver expects different parameters according to the Perl implementation anyway.  Should this be fixed in GhostDriver?

**Pull request merged**
