### PR TITLE
Upgrade to selenium 2.44.0

### PR DESCRIPTION
**Pull request by asolntsev**
- Upgrade to selenium-java 2.44.0
- Remove using deprecated (and now removed) method `Proxies.extractFrom`, see https://code.google.com/p/selenium/issues/detail?id=8088

### CODE REVIEW

**Comment by jvanderwee** [comment]
+1

**Comment by christopherbalz** [comment]
+1  - what andresriancho said.

**Comment by KabanaSoft** [comment]
Guys,

I'm trying to get a fix in place until an official release is made and am a little confused as to how to tell PhantomJs to use specific ghostdriver that contains the fix. I have grabbed the latest ghostdriver source from master and also downloaded the 1.2.1 fix mentioned by @asolntsev from here: http://mvnrepository.com/artifact/com.codeborne/phantomjsdriver/1.2.1.

I am using C# WebDriver bindings, running a selenium server 2.44.0 and PhantomJs 1.9.8. From my understanding PhantomJs has an old ghostdriver embedded into it that doesn't contain a fix for this issue, but you can override that using the phantomjs.ghostdriver.path option (i read this here: https://github.com/detro/ghostdriver/blob/master/README.md). I have tried using the following code to specify the custom ghostdriver path:

capabilities.SetCapability("phantomjs.ghostdriver.path", @"C:\ghostdriver-master\src\main.js");

I have tried many different options as well as pointing to the phantomjsdriver-1.2.1.jar file that i downloaded and still can't get it to work.

Do you have any suggestions on how i can get PhantomJs to use the updated ghostdriver that has this fix implemented? (i think im a little confused on exactly how to use this setting)

Any help would be greatly appreciated, thanks!

**Comment by luksch** [comment]
+1

Is there a problem with releasing this? I am still waiting desperately. 

BTW: Thanks you all for the work you put into this. My work could not be with selenium, phantomjs and the awesome ghostdriver.

**Comment by badem4o** [comment]
+1 What is the status of this issue?

**Comment by Robinfr** [comment]
+1 for releasing this.

**Comment by kpiwko** [comment]
Just as future note, Arquillian Drone and Graphene is migrating to com.codeborne fork. Selenium 2.45.0 was released recently and this issue takes 6 month to be released. Thanks @asolntsev for making that possible!

**Comment by rck109d** [comment]
+1

**Comment by bananajohnny** [comment]
+1

**Comment by automatictester** [comment]
+1

**Comment by lucaspouzac** [comment]
+1 :)

**Comment by djeikyb** [comment]
I'm not sure if I can trust @asolntsev. @kpiwko vouches for him, claiming the arquillian stuff is switching to his fork. But I don't know of @kpiwko either. You can verify this claim following transitive dependencies:

1. https://github.com/arquillian/arquillian-graphene/blob/87dd6253329ed55801ebcb955431b89aba9645bf/pom.xml

2. https://github.com/arquillian/arquillian-extension-drone/blob/8b54eb8915d217e1028fc82631fd966903c27fa2/drone-bom/pom.xml

3. https://github.com/qa/arquillian-phantom-driver/blob/c86f2749f8a99e1ed4233049c211a691d71d38ef/pom.xml

@kpiwko is apparently a RedHat employee, and you can see his contributions on this site. Since his claim checks out, it seems reasonable to transitively trust @asolntsev.

Just thought I'd mention this in case anyone else was a little hesitant to start using the @asolntsev fork.

**Comment by asolntsev** [comment]
Hi Djeikyb!

What i like about open-source development is that you don't need to
trust me. The only think in the World you can trust is the code. You
can just compare original phantomjs code and my fork and verify that
there is no more difference but the few required lines of code.

Sincerely yours,
@asolntsev


2015-04-16 16:06 GMT+08:00, djeikyb <notifications@github.com>:
> I'm not sure if I can trust @asolntsev. @kpiwko vouches for him, claiming
> the arquillian stuff is switching to his fork. But I don't know of @kpiwko
> either. You can verify this claim following transitive dependencies:
>
> 1.
> https://github.com/arquillian/arquillian-graphene/blob/87dd6253329ed55801ebcb955431b89aba9645bf/pom.xml
>
> 2.
> https://github.com/arquillian/arquillian-extension-drone/blob/8b54eb8915d217e1028fc82631fd966903c27fa2/drone-bom/pom.xml
>
> 3.
> https://github.com/qa/arquillian-phantom-driver/blob/c86f2749f8a99e1ed4233049c211a691d71d38ef/pom.xml
>
> @kpiwko is apparently a RedHat employee, and you can see his contributions
> on this site. Since his claim checks out, it seems reasonable to
> transitively trust @asolntsev.
>
> Just thought I'd mention this in case anyone else was a little hesitant to
> start using the @asolntsev fork.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/detro/ghostdriver/pull/399#issuecomment-93672368


-- 
Andrei Solntsev

**Comment by luksch** [comment]
@asolntsev do you have any knowledge about what actaully happened to this repo here? I mean why it is abandoned? Maybe there should be a message in the readme.me telling people that this repo is not maintained any more.

**Comment by erdi** [comment]
This repo doesn't look abandoned, @detro has made a commit 9hrs ago. There simply are no new releases for some reason...

**Comment by luksch** [comment]
That is good news! interesting timing for the first commit since November :) I would be more than glad if @detro continues his wonderful work!

**Comment by asolntsev** [comment]
Yes,
some months ago @detro wrote that he is not able to support the project anymore, and asked for volunteers. I guess he found somebody.

Sent from my HTC

----- Reply message -----

**Comment by GrayedFox** [comment]
This would resolve so many headaches on my end!!! +1 to release this asap.

**Comment by jnyman** [comment]
Just chiming in as others have done to see if a release is going to happen. If not, okay, but then let's make that abundantly clear to everyone. Incidentally, I came here via this ticket (https://github.com/detro/ghostdriver/issues/397). I'm using the solution provided there by @asolntsev and it's working fine.

Given that the "GhostDriver needs a proper maintainer" text is still on the readme, I'm guessing that a proper maintainer has not yet been found?

**Pull request merged**
